"use client"
import type React from "react"
import { createContext, useContext, useState, useEffect } from "react"

type Language = "fr" | "ar" | "en"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
  isRTL: boolean
}

const translations = {
  fr: {
    // Navigation
    "nav.dashboard": "Tableau de bord",
    "nav.bassins": "Bassins",
    "nav.capteurs": "Capteurs",
    "nav.alertes": "Alertes",
    "nav.rapports": "Rapports",
    "nav.parametres": "Paramètres",
    "nav.agents": "Agents terrain",
    "nav.ai_assistant": "Assistant IA",

    // Dashboard
    "dashboard.title": "Tableau de bord",
    "dashboard.subtitle": "Vue d'ensemble de votre système aquacole",
    "dashboard.system_operational": "Système opérationnel",
    "dashboard.last_update": "Dernière mise à jour: il y a 2 min",
    "dashboard.avg_temperature": "Température moyenne",
    "dashboard.avg_salinity": "Salinité moyenne",
    "dashboard.avg_ph": "pH moyen",
    "dashboard.dissolved_oxygen": "Oxygène dissous",
    "dashboard.bassins": "Bassins",
    "dashboard.capteurs": "Capteurs",
    "dashboard.alertes": "Alertes",
    "dashboard.active": "actifs",
    "dashboard.critical": "critiques",
    "dashboard.resolved": "résolues",
    "dashboard.trends": "Évolution des mesures",
    "dashboard.recent_alerts": "Alertes récentes",
    "dashboard.ai_insights": "Tendances IA",
    "dashboard.ai_subtitle": "Prédictions et recommandations basées sur l'intelligence artificielle",

    // Bassins
    "bassins.title": "Bassins",
    "bassins.subtitle": "Gestion et surveillance de vos bassins aquacoles",
    "bassins.new_bassin": "Nouveau bassin",
    "bassins.total": "Total bassins",
    "bassins.active": "Actifs",
    "bassins.alert": "En alerte",
    "bassins.maintenance": "Maintenance",
    "bassins.search": "Rechercher par nom ou ID...",
    "bassins.all_status": "Tous les statuts",
    "bassins.all_production": "Toutes productions",
    "bassins.list": "Liste des bassins",
    "bassins.overview": "Vue d'ensemble de tous vos bassins avec leurs paramètres actuels",
    "bassins.details": "Détails",
    "bassins.back": "Retour",
    "bassins.pdf_report": "Rapport PDF",
    "bassins.settings": "Paramètres",
    "bassins.location": "Localisation",
    "bassins.capacity": "Capacité",
    "bassins.production": "Production",
    "bassins.created": "Créé le",
    "bassins.edit": "Modifier le bassin",
    "bassins.delete": "Supprimer le bassin",
    "bassins.create": "Créer un bassin",

    // Capteurs
    "capteurs.title": "Capteurs",
    "capteurs.subtitle": "Surveillance et gestion de tous vos capteurs IoT",
    "capteurs.calibration": "Calibration",
    "capteurs.new_capteur": "Nouveau capteur",
    "capteurs.total": "Total capteurs",
    "capteurs.active": "Actifs",
    "capteurs.critical": "Critiques",
    "capteurs.disconnected": "Déconnectés",
    "capteurs.search": "Rechercher par ID ou bassin...",
    "capteurs.all_types": "Tous les types",
    "capteurs.all_status": "Tous les statuts",
    "capteurs.list": "Liste des capteurs",
    "capteurs.overview": "Vue d'ensemble de tous vos capteurs avec leur état actuel",
    "capteurs.details": "Détails",
    "capteurs.edit": "Modifier le capteur",
    "capteurs.delete": "Supprimer le capteur",
    "capteurs.create": "Créer un capteur",

    // Alertes
    "alertes.title": "Alertes",
    "alertes.subtitle": "Gestion des alertes et notifications du système",
    "alertes.total": "Total alertes",
    "alertes.critical": "Critiques",
    "alertes.in_progress": "En cours",
    "alertes.resolved": "Résolues",
    "alertes.search": "Rechercher par titre, bassin ou capteur...",
    "alertes.all_severity": "Toutes gravités",
    "alertes.all_status": "Tous les statuts",
    "alertes.list": "Liste des alertes",
    "alertes.overview": "Toutes les alertes du système avec leur statut de traitement",
    "alertes.treat": "Traiter",
    "alertes.treat_alert": "Traiter l'alerte",
    "alertes.update_status": "Mettre à jour le statut",
    "alertes.add_comment": "Ajouter un commentaire",

    // Rapports
    "rapports.title": "Rapports",
    "rapports.subtitle": "Génération et gestion des rapports d'analyse",
    "rapports.new_report": "Nouveau rapport",
    "rapports.sent_reports": "Rapports envoyés",
    "rapports.generated": "Généré",
    "rapports.sent": "Envoyé",
    "rapports.pending": "En attente",
    "rapports.failed": "Échec",
    "rapports.send_report": "Envoyer le rapport",
    "rapports.recipients": "Destinataires",
    "rapports.send_date": "Date d'envoi",
    "rapports.view_report": "Voir le rapport",
    "rapports.resend": "Renvoyer",

    // AI Assistant
    "ai.title": "Assistant IA",
    "ai.subtitle": "Prédictions et analyses intelligentes",
    "ai.predictions": "Prédictions",
    "ai.models": "Modèles IA",
    "ai.accuracy": "Précision",
    "ai.confidence": "Confiance",
    "ai.last_training": "Dernier entraînement",
    "ai.predictions_today": "Prédictions aujourd'hui",
    "ai.model_performance": "Performance des modèles",
    "ai.temperature_model": "Modèle Température",
    "ai.salinity_model": "Modèle Salinité",
    "ai.ph_model": "Modèle pH",
    "ai.oxygen_model": "Modèle Oxygène",

    // Agents
    "agents.title": "Agents terrain",
    "agents.subtitle": "Gestion des agents de terrain et affectations",
    "agents.new_agent": "Nouvel agent",
    "agents.total": "Total agents",
    "agents.available": "Disponibles",
    "agents.assigned": "Affectés",
    "agents.offline": "Hors ligne",
    "agents.search": "Rechercher par nom ou ID...",
    "agents.all_status": "Tous les statuts",
    "agents.all_zones": "Toutes les zones",
    "agents.list": "Liste des agents",
    "agents.overview": "Gestion des agents de terrain et leurs affectations",
    "agents.assign": "Affecter",
    "agents.remove": "Retirer",
    "agents.edit": "Modifier",
    "agents.create": "Créer un agent",
    "agents.delete": "Supprimer l'agent",

    // Common
    "common.save": "Sauvegarder",
    "common.cancel": "Annuler",
    "common.delete": "Supprimer",
    "common.edit": "Modifier",
    "common.view": "Voir",
    "common.close": "Fermer",
    "common.loading": "Chargement...",
    "common.search": "Rechercher",
    "common.filter": "Filtrer",
    "common.export": "Exporter",
    "common.import": "Importer",
    "common.status": "Statut",
    "common.actions": "Actions",
    "common.date": "Date",
    "common.time": "Heure",
    "common.name": "Nom",
    "common.type": "Type",
    "common.description": "Description",
    "common.create": "Créer",
    "common.update": "Mettre à jour",
    "common.confirm": "Confirmer",
    "common.yes": "Oui",
    "common.no": "Non",
    "common.success": "Succès",
    "common.error": "Erreur",
    "common.warning": "Attention",
    "common.info": "Information",

    // Forms
    "form.required": "Champ requis",
    "form.invalid_email": "Email invalide",
    "form.password_min": "Mot de passe trop court",
    "form.confirm_password": "Confirmer le mot de passe",
    "form.passwords_match": "Les mots de passe ne correspondent pas",

    // Messages
    "msg.delete_confirm": "Êtes-vous sûr de vouloir supprimer cet élément ?",
    "msg.action_success": "Action effectuée avec succès",
    "msg.action_error": "Erreur lors de l'exécution",
    "msg.no_data": "Aucune donnée disponible",
    "msg.loading": "Chargement en cours...",
  },

  ar: {
    // Navigation
    "nav.dashboard": "لوحة التحكم",
    "nav.bassins": "الأحواض",
    "nav.capteurs": "أجهزة الاستشعار",
    "nav.alertes": "التنبيهات",
    "nav.rapports": "التقارير",
    "nav.parametres": "الإعدادات",
    "nav.agents": "عمال الميدان",
    "nav.ai_assistant": "مساعد الذكاء الاصطناعي",

    // Dashboard
    "dashboard.title": "لوحة التحكم",
    "dashboard.subtitle": "نظرة عامة على نظام الاستزراع المائي الخاص بك",
    "dashboard.system_operational": "النظام يعمل",
    "dashboard.last_update": "آخر تحديث: منذ دقيقتين",
    "dashboard.avg_temperature": "متوسط درجة الحرارة",
    "dashboard.avg_salinity": "متوسط الملوحة",
    "dashboard.avg_ph": "متوسط الحموضة",
    "dashboard.dissolved_oxygen": "الأكسجين المذاب",
    "dashboard.bassins": "الأحواض",
    "dashboard.capteurs": "أجهزة الاستشعار",
    "dashboard.alertes": "التنبيهات",
    "dashboard.active": "نشط",
    "dashboard.critical": "حرج",
    "dashboard.resolved": "محلول",
    "dashboard.trends": "تطور القياسات",
    "dashboard.recent_alerts": "التنبيهات الأخيرة",
    "dashboard.ai_insights": "اتجاهات الذكاء الاصطناعي",
    "dashboard.ai_subtitle": "التنبؤات والتوصيات القائمة على الذكاء الاصطناعي",

    // Bassins
    "bassins.title": "الأحواض",
    "bassins.subtitle": "إدارة ومراقبة أحواض الاستزراع المائي",
    "bassins.new_bassin": "حوض جديد",
    "bassins.total": "إجمالي الأحواض",
    "bassins.active": "نشط",
    "bassins.alert": "تحت التنبيه",
    "bassins.maintenance": "صيانة",
    "bassins.search": "البحث بالاسم أو المعرف...",
    "bassins.all_status": "جميع الحالات",
    "bassins.all_production": "جميع الإنتاج",
    "bassins.list": "قائمة الأحواض",
    "bassins.overview": "نظرة عامة على جميع أحواضك مع معاملاتها الحالية",
    "bassins.details": "التفاصيل",
    "bassins.back": "العودة",
    "bassins.pdf_report": "تقرير PDF",
    "bassins.settings": "الإعدادات",
    "bassins.location": "الموقع",
    "bassins.capacity": "السعة",
    "bassins.production": "الإنتاج",
    "bassins.created": "تم الإنشاء في",
    "bassins.edit": "تعديل الحوض",
    "bassins.delete": "حذف الحوض",
    "bassins.create": "إنشاء حوض",

    // Capteurs
    "capteurs.title": "أجهزة الاستشعار",
    "capteurs.subtitle": "مراقبة وإدارة جميع أجهزة الاستشعار IoT",
    "capteurs.calibration": "المعايرة",
    "capteurs.new_capteur": "جهاز استشعار جديد",
    "capteurs.total": "إجمالي أجهزة الاستشعار",
    "capteurs.active": "نشط",
    "capteurs.critical": "حرج",
    "capteurs.disconnected": "منقطع",
    "capteurs.search": "البحث بالمعرف أو الحوض...",
    "capteurs.all_types": "جميع الأنواع",
    "capteurs.all_status": "جميع الحالات",
    "capteurs.list": "قائمة أجهزة الاستشعار",
    "capteurs.overview": "نظرة عامة على جميع أجهزة الاستشعار مع حالتها الحالية",
    "capteurs.details": "التفاصيل",
    "capteurs.edit": "تعديل جهاز الاستشعار",
    "capteurs.delete": "حذف جهاز الاستشعار",
    "capteurs.create": "إنشاء جهاز استشعار",

    // Alertes
    "alertes.title": "التنبيهات",
    "alertes.subtitle": "إدارة تنبيهات وإشعارات النظام",
    "alertes.total": "إجمالي التنبيهات",
    "alertes.critical": "حرج",
    "alertes.in_progress": "قيد التنفيذ",
    "alertes.resolved": "محلول",
    "alertes.search": "البحث بالعنوان أو الحوض أو جهاز الاستشعار...",
    "alertes.all_severity": "جميع مستويات الخطورة",
    "alertes.all_status": "جميع الحالات",
    "alertes.list": "قائمة التنبيهات",
    "alertes.overview": "جميع تنبيهات النظام مع حالة معالجتها",
    "alertes.treat": "معالجة",
    "alertes.treat_alert": "معالجة التنبيه",
    "alertes.update_status": "تحديث الحالة",
    "alertes.add_comment": "إضافة تعليق",

    // Rapports
    "rapports.title": "التقارير",
    "rapports.subtitle": "إنتاج وإدارة تقارير التحليل",
    "rapports.new_report": "تقرير جديد",
    "rapports.sent_reports": "التقارير المرسلة",
    "rapports.generated": "تم الإنتاج",
    "rapports.sent": "تم الإرسال",
    "rapports.pending": "في الانتظار",
    "rapports.failed": "فشل",
    "rapports.send_report": "إرسال التقرير",
    "rapports.recipients": "المستلمون",
    "rapports.send_date": "تاريخ الإرسال",
    "rapports.view_report": "عرض التقرير",
    "rapports.resend": "إعادة الإرسال",

    // AI Assistant
    "ai.title": "مساعد الذكاء الاصطناعي",
    "ai.subtitle": "التنبؤات والتحليلات الذكية",
    "ai.predictions": "التنبؤات",
    "ai.models": "نماذج الذكاء الاصطناعي",
    "ai.accuracy": "الدقة",
    "ai.confidence": "الثقة",
    "ai.last_training": "آخر تدريب",
    "ai.predictions_today": "التنبؤات اليوم",
    "ai.model_performance": "أداء النماذج",
    "ai.temperature_model": "نموذج درجة الحرارة",
    "ai.salinity_model": "نموذج الملوحة",
    "ai.ph_model": "نموذج الحموضة",
    "ai.oxygen_model": "نموذج الأكسجين",

    // Agents
    "agents.title": "عمال الميدان",
    "agents.subtitle": "إدارة عمال الميدان والمهام",
    "agents.new_agent": "عامل جديد",
    "agents.total": "إجمالي العمال",
    "agents.available": "متاح",
    "agents.assigned": "مكلف",
    "agents.offline": "غير متصل",
    "agents.search": "البحث بالاسم أو المعرف...",
    "agents.all_status": "جميع الحالات",
    "agents.all_zones": "جميع المناطق",
    "agents.list": "قائمة العمال",
    "agents.overview": "إدارة عمال الميدان ومهامهم",
    "agents.assign": "تكليف",
    "agents.remove": "إزالة",
    "agents.edit": "تعديل",
    "agents.create": "إنشاء عامل",
    "agents.delete": "حذف العامل",

    // Common
    "common.save": "حفظ",
    "common.cancel": "إلغاء",
    "common.delete": "حذف",
    "common.edit": "تعديل",
    "common.view": "عرض",
    "common.close": "إغلاق",
    "common.loading": "جاري التحميل...",
    "common.search": "بحث",
    "common.filter": "تصفية",
    "common.export": "تصدير",
    "common.import": "استيراد",
    "common.status": "الحالة",
    "common.actions": "الإجراءات",
    "common.date": "التاريخ",
    "common.time": "الوقت",
    "common.name": "الاسم",
    "common.type": "النوع",
    "common.description": "الوصف",
    "common.create": "إنشاء",
    "common.update": "تحديث",
    "common.confirm": "تأكيد",
    "common.yes": "نعم",
    "common.no": "لا",
    "common.success": "نجح",
    "common.error": "خطأ",
    "common.warning": "تحذير",
    "common.info": "معلومات",

    // Forms
    "form.required": "حقل مطلوب",
    "form.invalid_email": "بريد إلكتروني غير صالح",
    "form.password_min": "كلمة المرور قصيرة جداً",
    "form.confirm_password": "تأكيد كلمة المرور",
    "form.passwords_match": "كلمات المرور غير متطابقة",

    // Messages
    "msg.delete_confirm": "هل أنت متأكد من حذف هذا العنصر؟",
    "msg.action_success": "تم تنفيذ العملية بنجاح",
    "msg.action_error": "خطأ في تنفيذ العملية",
    "msg.no_data": "لا توجد بيانات متاحة",
    "msg.loading": "جاري التحميل...",
  },

  en: {
    // Navigation
    "nav.dashboard": "Dashboard",
    "nav.bassins": "Pools",
    "nav.capteurs": "Sensors",
    "nav.alertes": "Alerts",
    "nav.rapports": "Reports",
    "nav.parametres": "Settings",
    "nav.agents": "Field Agents",
    "nav.ai_assistant": "AI Assistant",

    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.subtitle": "Overview of your aquaculture system",
    "dashboard.system_operational": "System operational",
    "dashboard.last_update": "Last update: 2 min ago",
    "dashboard.avg_temperature": "Average temperature",
    "dashboard.avg_salinity": "Average salinity",
    "dashboard.avg_ph": "Average pH",
    "dashboard.dissolved_oxygen": "Dissolved oxygen",
    "dashboard.bassins": "Pools",
    "dashboard.capteurs": "Sensors",
    "dashboard.alertes": "Alerts",
    "dashboard.active": "active",
    "dashboard.critical": "critical",
    "dashboard.resolved": "resolved",
    "dashboard.trends": "Measurement trends",
    "dashboard.recent_alerts": "Recent alerts",
    "dashboard.ai_insights": "AI Insights",
    "dashboard.ai_subtitle": "Predictions and recommendations based on artificial intelligence",

    // Bassins
    "bassins.title": "Pools",
    "bassins.subtitle": "Management and monitoring of your aquaculture pools",
    "bassins.new_bassin": "New pool",
    "bassins.total": "Total pools",
    "bassins.active": "Active",
    "bassins.alert": "Alert",
    "bassins.maintenance": "Maintenance",
    "bassins.search": "Search by name or ID...",
    "bassins.all_status": "All statuses",
    "bassins.all_production": "All productions",
    "bassins.list": "Pool list",
    "bassins.overview": "Overview of all your pools with their current parameters",
    "bassins.details": "Details",
    "bassins.back": "Back",
    "bassins.pdf_report": "PDF Report",
    "bassins.settings": "Settings",
    "bassins.location": "Location",
    "bassins.capacity": "Capacity",
    "bassins.production": "Production",
    "bassins.created": "Created on",
    "bassins.edit": "Edit pool",
    "bassins.delete": "Delete pool",
    "bassins.create": "Create pool",

    // Capteurs
    "capteurs.title": "Sensors",
    "capteurs.subtitle": "Monitoring and management of all your IoT sensors",
    "capteurs.calibration": "Calibration",
    "capteurs.new_capteur": "New sensor",
    "capteurs.total": "Total sensors",
    "capteurs.active": "Active",
    "capteurs.critical": "Critical",
    "capteurs.disconnected": "Disconnected",
    "capteurs.search": "Search by ID or pool...",
    "capteurs.all_types": "All types",
    "capteurs.all_status": "All statuses",
    "capteurs.list": "Sensor list",
    "capteurs.overview": "Overview of all your sensors with their current state",
    "capteurs.details": "Details",
    "capteurs.edit": "Edit sensor",
    "capteurs.delete": "Delete sensor",
    "capteurs.create": "Create sensor",

    // Alertes
    "alertes.title": "Alerts",
    "alertes.subtitle": "System alerts and notifications management",
    "alertes.total": "Total alerts",
    "alertes.critical": "Critical",
    "alertes.in_progress": "In progress",
    "alertes.resolved": "Resolved",
    "alertes.search": "Search by title, pool or sensor...",
    "alertes.all_severity": "All severities",
    "alertes.all_status": "All statuses",
    "alertes.list": "Alert list",
    "alertes.overview": "All system alerts with their processing status",
    "alertes.treat": "Treat",
    "alertes.treat_alert": "Treat alert",
    "alertes.update_status": "Update status",
    "alertes.add_comment": "Add comment",

    // Rapports
    "rapports.title": "Reports",
    "rapports.subtitle": "Report generation and analysis management",
    "rapports.new_report": "New report",
    "rapports.sent_reports": "Sent reports",
    "rapports.generated": "Generated",
    "rapports.sent": "Sent",
    "rapports.pending": "Pending",
    "rapports.failed": "Failed",
    "rapports.send_report": "Send report",
    "rapports.recipients": "Recipients",
    "rapports.send_date": "Send date",
    "rapports.view_report": "View report",
    "rapports.resend": "Resend",

    // AI Assistant
    "ai.title": "AI Assistant",
    "ai.subtitle": "Intelligent predictions and analysis",
    "ai.predictions": "Predictions",
    "ai.models": "AI Models",
    "ai.accuracy": "Accuracy",
    "ai.confidence": "Confidence",
    "ai.last_training": "Last training",
    "ai.predictions_today": "Predictions today",
    "ai.model_performance": "Model performance",
    "ai.temperature_model": "Temperature Model",
    "ai.salinity_model": "Salinity Model",
    "ai.ph_model": "pH Model",
    "ai.oxygen_model": "Oxygen Model",

    // Agents
    "agents.title": "Field Agents",
    "agents.subtitle": "Field agents management and assignments",
    "agents.new_agent": "New agent",
    "agents.total": "Total agents",
    "agents.available": "Available",
    "agents.assigned": "Assigned",
    "agents.offline": "Offline",
    "agents.search": "Search by name or ID...",
    "agents.all_status": "All statuses",
    "agents.all_zones": "All zones",
    "agents.list": "Agent list",
    "agents.overview": "Field agents management and their assignments",
    "agents.assign": "Assign",
    "agents.remove": "Remove",
    "agents.edit": "Edit",
    "agents.create": "Create agent",
    "agents.delete": "Delete agent",

    // Common
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.view": "View",
    "common.close": "Close",
    "common.loading": "Loading...",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.export": "Export",
    "common.import": "Import",
    "common.status": "Status",
    "common.actions": "Actions",
    "common.date": "Date",
    "common.time": "Time",
    "common.name": "Name",
    "common.type": "Type",
    "common.description": "Description",
    "common.create": "Create",
    "common.update": "Update",
    "common.confirm": "Confirm",
    "common.yes": "Yes",
    "common.no": "No",
    "common.success": "Success",
    "common.error": "Error",
    "common.warning": "Warning",
    "common.info": "Information",

    // Forms
    "form.required": "Required field",
    "form.invalid_email": "Invalid email",
    "form.password_min": "Password too short",
    "form.confirm_password": "Confirm password",
    "form.passwords_match": "Passwords don't match",

    // Messages
    "msg.delete_confirm": "Are you sure you want to delete this item?",
    "msg.action_success": "Action completed successfully",
    "msg.action_error": "Error executing action",
    "msg.no_data": "No data available",
    "msg.loading": "Loading...",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("fr")

  const t = (key: string): string => {
    return translations[language][key as keyof (typeof translations)[typeof language]] || key
  }

  const isRTL = language === "ar"

  useEffect(() => {
    document.documentElement.dir = isRTL ? "rtl" : "ltr"
    document.documentElement.lang = language
  }, [language, isRTL])

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      <div className={isRTL ? "rtl" : "ltr"}>{children}</div>
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
